# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis
default_platform(:android)

platform :test do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build the solution and automatically rename Apk"
  lane :build do
    gradle(task: 'assemble',
    build_type: 'Release')
    sh("../shell/renameApk.sh")
    sh("../shell/renameDebugApk.sh")
    end
  end
